### ISSUE TITLE
Error: "You must authenticate via a GitHub App

### ISSUE THREAD

**Issue by alois-gaucher** [joshmfrankel/simplecov-check-action#7]
Hello,

I'm trying to integrate this action to a private repo, after trying to configure it I have this error that makes the action fail. Do you have any idea on how to fix this ?

/action/lib/coverage/utils/request.rb:48:in `run': Forbidden: {"message":"You must authenticate via a GitHub App.","documentation_url":"https://docs.github.com/rest/reference/checks#create-a-check-run"} (RuntimeError)

**Comment by joshmfrankel** [comment]
That sounds like your github_token is either invalid or missing. Did you use the `github_token: ${{ secrets.GITHUB_TOKEN }}` line from the basic installation example? https://github.com/joshmfrankel/simplecov-check-action#basic-installation. Do you have an example of your configuration?

**Comment by andriimokii** [comment]
Same here, token is in place with all permissions set
```
      - name: Run RSpec
        env:
          DB_NAME_TEST: ${{ secrets.POSTGRES_DB_TEST }}
          DB_USERNAME_TEST: ${{ secrets.POSTGRES_USER_TEST }}
          DB_PASSWORD_TEST: ${{ secrets.POSTGRES_PASSWORD_TEST }}
          RAILS_ENV: test
        run: |
          bin/rails db:migrate
          bundle exec rspec
      - uses: joshmfrankel/simplecov-check-action@main
        with:
          github_token: ${{ secrets.SIMPLECOV_ACTION_TOKEN }}
```
